[package]
name = "gping"
version = "1.13.1"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
repository = "https://github.com/orf/gping"
license = "MIT"
description = "Ping, but with a graph."
build = "build.rs"
readme = "../readme.md"

[dependencies]
pinger = { version = "^0.12.1", path = "../pinger" }
tui = { package = "ratatui", version = "0.21.0", features = ["crossterm"], default_features = false }
crossterm = "0.26.1"
anyhow = "1.0.72"
dns-lookup = "2.0.0"
chrono = "0.4.26"
itertools = "0.11.0"
shadow-rs = "0.23.0"
const_format = "0.2.31"
read_color = "1.0.0"
clap = { version = "4.3.15", features = ["derive"] }

[build-dependencies]
shadow-rs = "0.23.0"
